//! The main pipeline, end to end.

mod common;

use common::*;

#[test]
fn nothing_staged_is_a_clear_error() {
    let repo = Repo::new();
    let output = repo.wyckoff(&["-p", "mock"]);
    assert!(!output.status.success());
    assert!(
        stderr(&output).contains("nothing is staged"),
        "{}",
        stderr(&output)
    );
}

#[test]
fn a_missing_key_is_a_loud_error_not_a_made_up_message() {
    let repo = seeded_repo();
    // No key in the environment, so the provider cannot run: wyckoff must say
    // so instead of writing a message of its own.
    let output = repo.wyckoff(&["-p", "gemini"]);
    assert!(!output.status.success());
    let diagnostics = stderr(&output);
    assert!(diagnostics.contains("has no API key"), "{diagnostics}");
    assert!(diagnostics.contains("GEMINI_API_KEY"), "{diagnostics}");
    assert!(
        stdout(&output).trim().is_empty(),
        "no message should be printed: {}",
        stdout(&output)
    );
}

#[test]
fn mock_provider_completes_the_pipeline() {
    let repo = seeded_repo();
    let output = repo.wyckoff(&["-p", "mock", "--stats"]);
    assert!(output.status.success(), "{}", stderr(&output));
    assert!(!stdout(&output).trim().is_empty());

    let diagnostics = stderr(&output);
    assert!(diagnostics.contains("source: staged diff"), "{diagnostics}");
    assert!(diagnostics.contains("style:"), "{diagnostics}");
}

#[test]
fn json_output_is_machine_readable() {
    let repo = seeded_repo();
    let output = repo.wyckoff(&["-p", "mock", "--json"]);
    assert!(output.status.success(), "{}", stderr(&output));

    let value: serde_json::Value = serde_json::from_str(stdout(&output).trim()).unwrap();
    assert!(!value["subject"].as_str().unwrap().is_empty());
    assert_eq!(value["meta"]["source"], "staged");
}

#[test]
fn dry_run_shows_the_request_and_sends_nothing() {
    let repo = seeded_repo();
    let output = repo.wyckoff(&["-p", "mock", "--dry-run"]);
    assert!(output.status.success(), "{}", stderr(&output));

    let text = stdout(&output);
    assert!(text.contains("=== system ==="), "{text}");
    assert!(text.contains("NO type or scope prefixes"), "{text}");
    assert!(text.contains("## Project"), "{text}");
    assert!(text.contains("## Branch"), "{text}");
    assert!(text.contains("## Staged change"), "{text}");
    assert!(stderr(&output).contains("dry run"), "{}", stderr(&output));
}

#[test]
fn intent_is_carried_into_the_request() {
    let repo = seeded_repo();
    let output = repo.wyckoff(&["-p", "mock", "--dry-run", "-I", "unify page types"]);
    let text = stdout(&output);
    assert!(text.contains("unify page types"), "{text}");
    assert!(
        text.contains("The author's own words about this change"),
        "{text}"
    );
}

#[test]
fn the_context_file_reaches_the_prompt() {
    let repo = seeded_repo();
    let output = repo.wyckoff(&["-p", "mock", "--dry-run"]);
    let text = stdout(&output);
    assert!(
        text.contains("A tiny btree demo used by the tests"),
        "{text}"
    );
    assert!(text.contains("Project notes (from .context)"), "{text}");
}

#[test]
fn lockfile_noise_is_summarised_not_dumped() {
    let repo = seeded_repo();
    repo.write(
        "Cargo.lock",
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.229\"\n",
    );
    repo.git(&["add", "-A"]);

    let output = repo.wyckoff(&["-p", "mock", "--dry-run"]);
    let text = stdout(&output);
    assert!(
        text.contains("added Cargo.lock (+6 -0)") || text.contains("modified Cargo.lock"),
        "the lockfile should be a one-liner: {text}"
    );
    assert!(
        !text.contains("automatically @generated by Cargo"),
        "lockfile bodies must not be sent: {text}"
    );
    assert!(
        !text.contains("[[package]]"),
        "lockfile bodies must not be sent: {text}"
    );
}
